apiVersion: apps/v1
kind: Deployment
metadata:
  name: react_app
  labels:
    app: react_app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react_app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: react_app
    spec:
      containers:
        - image: nelhombre/react_app:latest
          imagePullPolicy: Always
          name: react_app
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: react_app
  labels:
    app: react_app
spec:
  type: LoadBalancer
  selector:
    app: react_app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
      protocol: TCP
